### ISSUE TITLE
Basic Sql Request failed 

### ISSUE THREAD

**Issue by huangsusu** [shi-yuan/elasticsearch-sql-site-chrome#2]
Today, I installed elasticsearch 6.2.2, run and loaded this project as a chrome app.
Finally do a simple test, but it failed.
![image](https://user-images.githubusercontent.com/13460236/54223266-59a07200-44b4-11e9-9daa-24dfcb711ba7.png)

Could you kindly help take a look? Thanks in advance!!

**Comment by huangsusu** [comment]
Additionally, I have installed sql-plugin and set "http.cors.enabled" as true on ES side.

**Comment by shi-yuan** [comment]
http://localhost:9200/

**Comment by huangsusu** [comment]
Do you mean putting the url into the top-right input box or chrome?
![image](https://user-images.githubusercontent.com/13460236/54318529-dd855780-45a3-11e9-9758-271b561b6c3e.png)
![image](https://user-images.githubusercontent.com/13460236/54318729-787e3180-45a4-11e9-88ea-69006ab3401c.png)
Could you give more tips?

**Comment by shi-yuan** [comment]
explain ？what's your http status？what‘s es log？

**Comment by ZDL-Git** [comment]
Same question +1

**Comment by shi-yuan** [comment]
put the url into the top-right input box：

http://localhost:9200/

**Comment by ZDL-Git** [comment]
It works, thanks
