### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by aogg** [shi-yuan/elasticsearch-sql-site-chrome#4]
{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_nlpcn], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_nlpcn"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_nlpcn], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_nlpcn"},"status":400}

**Comment by aogg** [comment]
![image](https://user-images.githubusercontent.com/8998031/131213103-959bb438-d06c-450c-a69e-86ff309ef53e.png)

**Comment by shi-yuan** [comment]
请求路径变更过：https://github.com/NLPchina/elasticsearch-sql#important

更新到最新版试试

**Comment by aogg** [comment]
这个ui工具是不是不支持7以上的版本

**Comment by aogg** [comment]
文档有些地方
